version: '3'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    command: sh -c "swag init && go run main.go"
    environment:
      - REDIS_ADDRESS=redis:6379
  test:
    build: .
    depends_on:
      - redis
    command: sh -c "go test -v ./..."
    environment:
      - REDIS_ADDRESS=redis:6379